### ISSUE TITLE
Doc still references tactician

### ISSUE THREAD

**Issue by jon-ht** [jorge07/symfony-5-es-cqrs-boilerplate#147]
This file seems outdated since Messenger replaced Tactician

https://github.com/jorge07/symfony-5-es-cqrs-boilerplate/blob/7272cd84931d43cfcf4173c459ac826186be43b2/doc/GetStarted/Buses.md

**Comment by jorge07** [comment]
Totally right. I'll find time this weekend to add the messenger documentation. Thanks for report it!
