### ISSUE TITLE
Sign-in form returns a JSON response

### ISSUE THREAD

**Issue by jon-ht** [jorge07/symfony-5-es-cqrs-boilerplate#148]
When I try to log in with an invalid email (like `foo`), I'm getting an error `"Not a valid email"` but the response is in JSON

![image](https://user-images.githubusercontent.com/17051512/81339720-e9d54980-90ae-11ea-8e6f-7b2ef5b74d23.png)

Do you have any idea why the `AuthenticationException` isn't caught by firewall or isn't a basic HttpResponse ?

---

Edit: I'm trying to log via `http://127.0.0.1/sign-in` in the web form

**Comment by cv65kr** [comment]
Hey

If you look at `\App\Infrastructure\User\Auth\Guard\LoginAuthenticator::getUser` only `InvalidCredentialsException` is catched and throwed again as `AuthenticationException`.

Incomming data is validate by Assertion and when fail they throws `InvalidArgumentException` which is not catched.

**Comment by jorge07** [comment]
Strange, this is covered [here](https://github.com/jorge07/symfony-5-es-cqrs-boilerplate/blob/master/src/UI/Http/Web/Controller/SignUpController.php#L61-L62) and there's a test for this use case: https://github.com/jorge07/symfony-5-es-cqrs-boilerplate/blob/master/tests/UI/Http/Web/Controller/SignUpControllerTest.php#L50

I tried to reproduce it locally but I can't get this JSON response...

**Comment by jorge07** [comment]
Is this a simple clone? No edits?

**Comment by cv65kr** [comment]
you looked at `sign-up` but problem is with `sign-in` 😄

**Comment by jorge07** [comment]
🤦 That's why I shouldn't do stuff at 2AM

**Comment by jorge07** [comment]
Fixed here https://github.com/jorge07/symfony-5-es-cqrs-boilerplate/pull/149/commits/914eb0c2bac18e3777c20ac871c5fd88b2f3b0af

**Comment by jorge07** [comment]
Close as fixed in #149 
thanks for report it!

**Comment by jon-ht** [comment]
Thanks for the quick fix! :)
