### ISSUE TITLE
UserView::serialize | created_at field

### ISSUE THREAD

**Issue by abelardolg** [jorge07/symfony-5-es-cqrs-boilerplate#175]
Hi there,

1: I think it's a typo at the line 25 of this class.

2: inside the serialize method the "created_at" and "updated_at" fields are not returning inside the array : is it ok?

Best regards.

**Comment by jorge07** [comment]
Hi @abelardolg 

1 - True, will submit a patch

2 - True, it depends how much data you want to expose.

I also rethinking about the read model to avoid serialisation as much as possible to expect modifications in this side

thanks

**Comment by jorge07** [comment]
Closed by mistake. I'm working on a fix for this, plus some optimization in the serializer side

**Comment by jorge07** [comment]
#184 fixed in
