### ISSUE TITLE
Retrieving user data | Traits

### ISSUE THREAD

**Issue by abelardolg** [jorge07/symfony-5-es-cqrs-boilerplate#178]
Hi there,
I wonder if a trail is a good choice to retrieve the user data in those controllers which need this information to process their requests.

Best regards.

**Comment by jorge07** [comment]
You mean trait?

Could be an option but you'll add as requirement the session so need to add a setter (which I do not like for this kind of things as I try to avoid optional dependencies) or modify the construct. What about an abstract controller?

```php
<?php

declare(strict_types=1);

namespace App\UI\Http\Rest\Controller;

use App\Infrastructure\Share\Bus\Command\CommandBus;
use App\Infrastructure\Share\Bus\Query\QueryBus;
use App\Infrastructure\User\Auth\Session;
use App\UI\Http\Rest\Controller\CommandController;

abstract class SessionAwareController extends CommandQueryController
{
    private Session $session;

    public function __construct(
        Session $session, 
        CommandBus $commandBus,
        QueryBus $queryBus
    )  {
        parent::__construct($commandBus);

        $this->session = $session;
    }

    /**
     * @returns [ 'uuid': string, 'username': string, 'roles': array<string>]
     * @throws App\Domain\User\Exception\InvalidCredentialsException
     */
    protected function userFromSession(): array
        return $this->session->get()
    }
}
```

**Comment by abelardolg** [comment]
Yes, I meant trait not "Trail"! Sorry!

**Comment by abelardolg** [comment]
Regarding your suggestion to add an AbstractController:
It would be a good idea to add a method to retrieve the user data inside the base controller AbstractRenderController. 

Ps: Yes, I meant "trait" not "trail".🙊

**Comment by jorge07** [comment]
I think this will depend of each app and needs to be implemented just when needed. Don't see a real benefit add it to the boilerplate.

I'm closing the issue ;)
