### ISSUE TITLE
Instalar proyecto e iniciar

### ISSUE THREAD

**Issue by bareser** [jorge07/symfony-5-es-cqrs-boilerplate#179]
Hola, estoy trasteando con este proyecto plantilla y hasta ahora he hecho:

- Clonar con git

- he lanzado: make start

- he lanzado: make phpunit

he comprobado que los contenedores están activos y creo que no me falta nada más.
Mi duda es donde o como puedo ver las distintas URLs para probar por mi mismo el proyecto. ¿Qué URLs tiene este proyecto?
Intento acceder aqui http://127.0.0.1/api/doc pero no me funciona.

¿Me queda algo por instalar o hacer?

Gracias de antemano.

**Comment by jorge07** [comment]
Hola @bareser 

Es un clone nuevo o una copia de hace tiempo? Me puedes pegar el hash de tu HEAD y el output de `docker ps`?
En que plataforma estás windows|linux|osx?

**Comment by jorge07** [comment]
No puedo reproducir tu problema desde local:
```sh

symfony-5-es-cqrs-boilerplate on  master via 🐘 v7.3.11 on 🐳 v19.03.5 via (dockerd) at ☸️  minikube took 2s
➜ curl -I http://$(dinghy ip)/api/doc.json
HTTP/1.1 200 OK
Server: nginx/1.17.10
Content-Type: application/json
Connection: keep-alive
X-Powered-By: PHP/7.4.3
Cache-Control: no-cache, private
Date: Sun, 05 Jul 2020 18:33:02 GMT
X-Debug-Token: e64d7e
X-Debug-Token-Link: http://192.168.99.106/_profiler/e64d7e
X-Robots-Tag: noindex

symfony-5-es-cqrs-boilerplate on  master via 🐘 v7.3.11 on 🐳 v19.03.5 via (dockerd) at ☸️  minikube
➜ curl -I http://$(dinghy ip)/api/doc
HTTP/1.1 200 OK
Server: nginx/1.17.10
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.4.3
Cache-Control: no-cache, private
Date: Sun, 05 Jul 2020 18:33:06 GMT
X-Debug-Token: 652dda
X-Debug-Token-Link: http://192.168.99.106/_profiler/652dda
X-Robots-Tag: noindex

symfony-5-es-cqrs-boilerplate on  master via 🐘 v7.3.11 on 🐳 v19.03.5 via (dockerd) at ☸️  minikube
➜ history
11343  cd work/qa
11346  git clone git@github.com:jorge07/symfony-5-es-cqrs-boilerplate.git
11347  cd symfony-5-es-cqrs-boilerplate
11348  dinghy status
11349  eval $(dinghy env)
11350  make start
11351  curl -I http://$(dinghy ip)/api/doc.json
11352  curl -I http://$(dinghy ip)/api/doc

```

**Comment by bareser** [comment]
He vuelto a actualizar el repositorio y ya me funciona, accedo perfectamente a localhost, sería algo puntual de la versión que yo me descargué. Gracias @jorge07 
Solo una duda más: ¿puede acceder a RabbitMQ y a ElasticSearch desde una URL? me imagino que estas herramientas dispondrán de algun portal para gestionarlos tipo BBDD (phpmyadmin, etc...)

**Comment by bareser** [comment]
@jorge07 estoy desarrollando en windows con WSL2 (ubuntu) y por el momento me va muy fino! o eso creo.

**Comment by jorge07** [comment]
Puedes ver los puertos de elastic y rabbitmq en el docker compose de `etc/env/dev`

Cierro issue si está resuelta :)
