### ISSUE TITLE
Replace Broadway

### ISSUE THREAD

**Issue by jorge07** [jorge07/symfony-5-es-cqrs-boilerplate#82]
More than a year without broadway release and seems quite out of date.

Options:
 - [eventsauce](https://github.com/eventsaucephp/eventsauce)?
 - [prooph](https://github.com/prooph/event-sourcing)?
 - Create a new one....?

**Comment by rogerguasch** [comment]
Maybe using the new **messenger component**?

more info:
- https://stefanoalletti.wordpress.com/2018/08/10/cqrs-is-easy-with-symfony-4-and-his-messanger-component/
- https://symfony.com/doc/current/components/messenger.html

**Comment by jorge07** [comment]
The symfony messenger library is about transport but not about DDD or Event sourcing.
BTW the pr for symfony messenger is open and still wip. I really want to see it working

**Comment by rogerguasch** [comment]
From the official documentation of **eventsauce**:

> The library is focused purely around event sourcing, not full-blown CQRS/ES. If you need that, I recommend checking out Prooph or Broadway. These libraries have a higher level of entry but provide an “everything you need is right here” experience.

**Comment by rogerguasch** [comment]
and the future of prooph... https://www.sasaprolic.com/2018/08/the-future-of-prooph-components.html

> Service-Bus:
When it was originally developed, there was no good alternative out there. In the meantime symfony shipped its own messenger component (I looked into it, it looks really great!) and sooner or later, it will probably have more downloads then our famous service-bus implementation.

**Comment by jorge07** [comment]
@rogerguasch thanks a lot for all this info. I start thinking in prooph as only real alternative out there

**Comment by blixit** [comment]
My experience of prooph was not really good. It was simple to understand but I didn't appreciate use of mysql statements directly. Maybe they now offer doctrine integration (actually I didnt check new releases for a while).
You should also pay attention to their code.
I think you should create a new one. Seeing the number of stargazers you should be able to find contributors.

**Comment by Lutacon** [comment]
Broadway just tag a new release 2.1

**Comment by jorge07** [comment]
Still missing some important features for us like reply events -> https://github.com/broadway/broadway/pull/361

**Comment by jorge07** [comment]
At least I guess I'll be able to upgrade to symfony 4.2

**Comment by Lutacon** [comment]
IIRC with this new release, we could upgrade phpstan and some other packages.

But we should definitely look for a replacement here.

**Comment by jorge07** [comment]
Thinking about implement event replay abstraction and snapshots here and close this issue as broadway seems good enough

**Comment by jorge07** [comment]
Closing as we haven't found any better
